make LogTable always signed char
char is signed by default on x86 but unsigned on some arm platforms
but the table needs to contain -1 and this leads to errors like this:

src/component_types/base_packed_component.h: In static member function ‘static unsigned int BasePackedComponent::log2(unsigned int)’:
src/component_types/base_packed_component.h:128:10: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]